name: "Node.js Script Scheduler"
version: "1.0.11"
slug: "node_scheduler"
description: "Run custom Node.js scripts on a schedule."
url: "https://github.com/kewang/ha-nodejs-scheduler"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
services:
  - "mqtt:need"
map:
  - config:rw
options:
  mqtt_host: ""
  mqtt_user: ""
  mqtt_pass: ""
  scripts: []
schema:
  mqtt_host: str?
  mqtt_user: str?
  mqtt_pass: password?
  scripts:
    - path: str
      cron: str
      env_vars: str?
