name: "Node.js Script Scheduler"
version: "1.0.16"
slug: "node_scheduler"
description: "Run custom Node.js scripts on a schedule."
url: "https://github.com/kewang/ha-nodejs-scheduler"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
services:
  - "mqtt:need"
map:
  - config:rw
options:
  mqtt_host: ""
  mqtt_user: ""
  mqtt_pass: ""
  scripts: []
schema:
  mqtt_host: str?
  mqtt_user: str?
  mqtt_pass: password?
  scripts:
    - path: match(app_scripts/power_outage.js)
      cron: str
      env_vars:
        POWER_STATION_NAME: str
        POWER_STATION_AREA: str
        OUTAGE_KEYWORD: str
    - path: match(app_scripts/water_outage.js)
      cron: str
      env_vars:
        OUTAGE_CITY: str
        OUTAGE_DISTRICT: str
        OUTAGE_AREA: str
    - path: match(app_scripts/water_quality.js)
      cron: str
      env_vars:
        STATION_ID: str
    - path: str
      cron: str
      env_vars: str?
