name: Node.js Runner
version: "1.0.0"
slug: nodejs_runner
description: Run various Node.js scripts inside one Add-on
startup: application
boot: auto
options:
  SCRIPT: hello.js
schema:
  SCRIPT: str
arch:
  - aarch64
  - amd64
