name: "Node.js Script Scheduler"
version: "1.0.2"
slug: "node_scheduler"
description: "Run custom Node.js scripts on a schedule."
arch:
  - aarch64
  - amd64
  - armv7
startup: application
map:
  - config:rw
options:
  scripts: []
schema:
  scripts:
    - path: str
      cron: str
      env_vars: str?